-- ============================================================
-- OracleDB - Table DDL for module-inventory
-- Table Prefix: MOD_INVENTORY_
-- Connect as: inventory_user
-- ============================================================

-- ============================================================
-- Sequences
-- ============================================================

CREATE SEQUENCE MOD_INVENTORY_ITEMS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE MOD_INVENTORY_STORAGE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ============================================================
-- Table: MOD_INVENTORY_ITEMS
-- Description: Inventory items master table
-- ============================================================

CREATE TABLE MOD_INVENTORY_ITEMS (
    ITEM_ID           NUMBER(19)    DEFAULT MOD_INVENTORY_ITEMS_SEQ.NEXTVAL PRIMARY KEY,
    ITEM_CODE         VARCHAR2(50)  NOT NULL,
    ITEM_NAME         VARCHAR2(200) NOT NULL,
    CATEGORY          VARCHAR2(100),
    QUANTITY          NUMBER(10)    DEFAULT 0 NOT NULL,
    UNIT_PRICE        NUMBER(18,2),
    STORAGE_LOCATION  VARCHAR2(200),
    DESCRIPTION       VARCHAR2(500),
    USE_YN            CHAR(1)       DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CREATED_BY        VARCHAR2(50),
    UPDATED_BY        VARCHAR2(50),
    CONSTRAINT UK_MOD_INV_ITEM_CODE UNIQUE (ITEM_CODE),
    CONSTRAINT CK_MOD_INV_ITEM_USEYN CHECK (USE_YN IN ('Y', 'N'))
);

COMMENT ON TABLE  MOD_INVENTORY_ITEMS                  IS 'Inventory Items Master';
COMMENT ON COLUMN MOD_INVENTORY_ITEMS.ITEM_ID          IS 'Item Primary Key (Auto Sequence)';
COMMENT ON COLUMN MOD_INVENTORY_ITEMS.ITEM_CODE        IS 'Unique Item Code';
COMMENT ON COLUMN MOD_INVENTORY_ITEMS.ITEM_NAME        IS 'Item Name';
COMMENT ON COLUMN MOD_INVENTORY_ITEMS.CATEGORY         IS 'Item Category';
COMMENT ON COLUMN MOD_INVENTORY_ITEMS.QUANTITY          IS 'Current Stock Quantity';
COMMENT ON COLUMN MOD_INVENTORY_ITEMS.UNIT_PRICE       IS 'Unit Price';
COMMENT ON COLUMN MOD_INVENTORY_ITEMS.STORAGE_LOCATION IS 'Storage Location Code';
COMMENT ON COLUMN MOD_INVENTORY_ITEMS.DESCRIPTION      IS 'Item Description';
COMMENT ON COLUMN MOD_INVENTORY_ITEMS.USE_YN           IS 'Active Flag (Y/N)';

-- ============================================================
-- Table: MOD_INVENTORY_STORAGE_LOCATIONS
-- Description: 3D storage location coordinates
-- ============================================================

CREATE TABLE MOD_INVENTORY_STORAGE_LOCATIONS (
    LOCATION_ID    NUMBER(19)    DEFAULT MOD_INVENTORY_STORAGE_SEQ.NEXTVAL PRIMARY KEY,
    LOCATION_CODE  VARCHAR2(50)  NOT NULL,
    LOCATION_NAME  VARCHAR2(200) NOT NULL,
    ZONE           VARCHAR2(50),
    COORD_X        NUMBER(10,4),
    COORD_Y        NUMBER(10,4),
    COORD_Z        NUMBER(10,4),
    CAPACITY       NUMBER(10),
    CURRENT_USAGE  NUMBER(10)    DEFAULT 0,
    USE_YN         CHAR(1)       DEFAULT 'Y' NOT NULL,
    CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_MOD_INV_LOC_CODE UNIQUE (LOCATION_CODE),
    CONSTRAINT CK_MOD_INV_LOC_USEYN CHECK (USE_YN IN ('Y', 'N'))
);

COMMENT ON TABLE  MOD_INVENTORY_STORAGE_LOCATIONS                IS '3D Storage Locations';
COMMENT ON COLUMN MOD_INVENTORY_STORAGE_LOCATIONS.LOCATION_ID    IS 'Location Primary Key (Auto Sequence)';
COMMENT ON COLUMN MOD_INVENTORY_STORAGE_LOCATIONS.LOCATION_CODE  IS 'Unique Location Code';
COMMENT ON COLUMN MOD_INVENTORY_STORAGE_LOCATIONS.LOCATION_NAME  IS 'Location Name';
COMMENT ON COLUMN MOD_INVENTORY_STORAGE_LOCATIONS.ZONE           IS 'Warehouse Zone';
COMMENT ON COLUMN MOD_INVENTORY_STORAGE_LOCATIONS.COORD_X        IS '3D X Coordinate';
COMMENT ON COLUMN MOD_INVENTORY_STORAGE_LOCATIONS.COORD_Y        IS '3D Y Coordinate';
COMMENT ON COLUMN MOD_INVENTORY_STORAGE_LOCATIONS.COORD_Z        IS '3D Z Coordinate';
COMMENT ON COLUMN MOD_INVENTORY_STORAGE_LOCATIONS.CAPACITY       IS 'Max Storage Capacity';
COMMENT ON COLUMN MOD_INVENTORY_STORAGE_LOCATIONS.CURRENT_USAGE  IS 'Current Usage Count';
COMMENT ON COLUMN MOD_INVENTORY_STORAGE_LOCATIONS.USE_YN         IS 'Active Flag (Y/N)';

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX IDX_MOD_INV_ITEM_CATEGORY ON MOD_INVENTORY_ITEMS (CATEGORY);
CREATE INDEX IDX_MOD_INV_ITEM_USEYN    ON MOD_INVENTORY_ITEMS (USE_YN);
CREATE INDEX IDX_MOD_INV_ITEM_STORAGE  ON MOD_INVENTORY_ITEMS (STORAGE_LOCATION);

CREATE INDEX IDX_MOD_INV_LOC_ZONE      ON MOD_INVENTORY_STORAGE_LOCATIONS (ZONE);
CREATE INDEX IDX_MOD_INV_LOC_USEYN     ON MOD_INVENTORY_STORAGE_LOCATIONS (USE_YN);
