-- ============================================================
-- OracleDB - Sample Data for module-inventory
-- Connect as: inventory_user
-- ============================================================

-- Storage Locations (3D Coordinates)
INSERT INTO MOD_INVENTORY_STORAGE_LOCATIONS (LOCATION_CODE, LOCATION_NAME, ZONE, COORD_X, COORD_Y, COORD_Z, CAPACITY, CURRENT_USAGE)
VALUES ('LOC-A01-01', 'Zone A - Rack 01 - Level 01', 'ZONE-A', 1.0, 1.0, 1.0, 100, 45);

INSERT INTO MOD_INVENTORY_STORAGE_LOCATIONS (LOCATION_CODE, LOCATION_NAME, ZONE, COORD_X, COORD_Y, COORD_Z, CAPACITY, CURRENT_USAGE)
VALUES ('LOC-A01-02', 'Zone A - Rack 01 - Level 02', 'ZONE-A', 1.0, 1.0, 2.0, 100, 30);

INSERT INTO MOD_INVENTORY_STORAGE_LOCATIONS (LOCATION_CODE, LOCATION_NAME, ZONE, COORD_X, COORD_Y, COORD_Z, CAPACITY, CURRENT_USAGE)
VALUES ('LOC-B01-01', 'Zone B - Rack 01 - Level 01', 'ZONE-B', 5.0, 1.0, 1.0, 200, 150);

INSERT INTO MOD_INVENTORY_STORAGE_LOCATIONS (LOCATION_CODE, LOCATION_NAME, ZONE, COORD_X, COORD_Y, COORD_Z, CAPACITY, CURRENT_USAGE)
VALUES ('LOC-B02-01', 'Zone B - Rack 02 - Level 01', 'ZONE-B', 5.0, 3.0, 1.0, 150, 0);

INSERT INTO MOD_INVENTORY_STORAGE_LOCATIONS (LOCATION_CODE, LOCATION_NAME, ZONE, COORD_X, COORD_Y, COORD_Z, CAPACITY, CURRENT_USAGE)
VALUES ('LOC-C01-01', 'Zone C - Rack 01 - Level 01', 'ZONE-C', 10.0, 1.0, 1.0, 300, 280);

-- Inventory Items
INSERT INTO MOD_INVENTORY_ITEMS (ITEM_CODE, ITEM_NAME, CATEGORY, QUANTITY, UNIT_PRICE, STORAGE_LOCATION, DESCRIPTION)
VALUES ('ITM-001', 'Electronic Component A', 'ELECTRONICS', 500, 12.50, 'LOC-A01-01', 'Standard electronic component type A');

INSERT INTO MOD_INVENTORY_ITEMS (ITEM_CODE, ITEM_NAME, CATEGORY, QUANTITY, UNIT_PRICE, STORAGE_LOCATION, DESCRIPTION)
VALUES ('ITM-002', 'Mechanical Part B', 'MECHANICAL', 200, 45.00, 'LOC-A01-02', 'Precision mechanical part type B');

INSERT INTO MOD_INVENTORY_ITEMS (ITEM_CODE, ITEM_NAME, CATEGORY, QUANTITY, UNIT_PRICE, STORAGE_LOCATION, DESCRIPTION)
VALUES ('ITM-003', 'Chemical Reagent C', 'CHEMICALS', 50, 120.00, 'LOC-B01-01', 'Laboratory chemical reagent type C');

INSERT INTO MOD_INVENTORY_ITEMS (ITEM_CODE, ITEM_NAME, CATEGORY, QUANTITY, UNIT_PRICE, STORAGE_LOCATION, DESCRIPTION)
VALUES ('ITM-004', 'Packaging Material D', 'PACKAGING', 3, 5.25, 'LOC-B01-01', 'Standard packaging material - LOW STOCK');

INSERT INTO MOD_INVENTORY_ITEMS (ITEM_CODE, ITEM_NAME, CATEGORY, QUANTITY, UNIT_PRICE, STORAGE_LOCATION, DESCRIPTION)
VALUES ('ITM-005', 'Safety Equipment E', 'SAFETY', 75, 89.99, 'LOC-C01-01', 'Personal safety equipment type E');

COMMIT;
