-- ============================================================
-- STKKA Table DDL
-- Generated from STKKY_TABLE_ROW.xlsx
-- Total columns: 128
-- Primary Key: STOKKY (재고키)
-- ============================================================

-- Drop table if exists
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE STKKA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE STKKA (
    STOKKY               NUMBER(20) NOT NULL,
    WAREKY               NUMBER(10) NOT NULL,
    LOTNUM               VARCHAR2(30) NOT NULL,
    LOCAKY               VARCHAR2(20) NOT NULL,
    TRNUID               VARCHAR2(50),
    SECTID               VARCHAR2(20),
    PACKID               VARCHAR2(50),
    QTSIWH               NUMBER(18,4),
    QTSALO               NUMBER(18,4),
    QTSPMO               NUMBER(18,4),
    QTSPMI               NUMBER(18,4),
    QTSBLK               NUMBER(18,4),
    QTYUOM               NUMBER(18,4),
    TRUNTY               VARCHAR2(10),
    MEASKY               VARCHAR2(30),
    UOMKEY               VARCHAR2(10),
    QTPUOM               NUMBER(10),
    DUOMKY               VARCHAR2(10),
    QTDUOM               NUMBER(10),
    TKFLKY               VARCHAR2(20),
    STEPNO               VARCHAR2(10),
    LSTTFL               VARCHAR2(10),
    SRCSKY               VARCHAR2(30),
    UOMDOC               VARCHAR2(10),
    CNTBSK               NUMBER(10),
    NUPDPS               VARCHAR2(10),
    REFDKY               VARCHAR2(20),
    REFDIT               VARCHAR2(10),
    REFCAT               VARCHAR2(10),
    REFDAT               NUMBER(8),
    PURCKY               VARCHAR2(20),
    PURCIT               VARCHAR2(10),
    ASNDKY               VARCHAR2(20),
    ASNDIT               VARCHAR2(10),
    RECVKY               VARCHAR2(30),
    RECVIT               VARCHAR2(10),
    SHPOKY               VARCHAR2(20),
    SHPOIT               VARCHAR2(10),
    GRPOKY               VARCHAR2(20),
    GRPOIT               VARCHAR2(10),
    TASKKY               VARCHAR2(20),
    TASKIT               VARCHAR2(10),
    SADJKY               VARCHAR2(20),
    SADJIT               VARCHAR2(10),
    SDIFKY               VARCHAR2(20),
    SDIFIT               VARCHAR2(10),
    PHYIKY               VARCHAR2(20),
    PHYIIT               VARCHAR2(10),
    OWNRKY               VARCHAR2(10),
    SKUKEY               VARCHAR2(30),
    LOTA01               VARCHAR2(10),
    LOTA02               VARCHAR2(10),
    LOTA03               VARCHAR2(10),
    LOTA04               VARCHAR2(10),
    LOTA05               VARCHAR2(20),
    LOTA06               VARCHAR2(10),
    LOTA07               VARCHAR2(20),
    LOTA08               VARCHAR2(10),
    LOTA09               VARCHAR2(10),
    LOTA10               VARCHAR2(30),
    LOTA11               NUMBER(8),
    LOTA12               NUMBER(8),
    LOTA13               VARCHAR2(20),
    LOTA14               VARCHAR2(20),
    LOTA15               VARCHAR2(20),
    LOTA16               NUMBER(10),
    LOTA17               VARCHAR2(10),
    LOTA18               NUMBER(10),
    LOTA19               NUMBER(10),
    LOTA20               NUMBER(10),
    AWMSNO               VARCHAR2(20),
    DESC01               VARCHAR2(200),
    DESC02               VARCHAR2(100),
    ASKU01               VARCHAR2(30),
    ASKU02               VARCHAR2(30),
    ASKU03               VARCHAR2(30),
    ASKU04               NUMBER(10),
    ASKU05               VARCHAR2(10),
    EANCOD               VARCHAR2(30),
    GTINCD               VARCHAR2(30),
    SKUG01               VARCHAR2(10),
    SKUG02               VARCHAR2(10),
    SKUG03               VARCHAR2(10),
    SKUG04               VARCHAR2(10),
    SKUG05               VARCHAR2(10),
    GRSWGT               NUMBER(18,4),
    NETWGT               NUMBER(18,4),
    WGTUNT               VARCHAR2(10),
    LENGTH               NUMBER(18,4),
    WIDTHW               NUMBER(18,4),
    HEIGHT               NUMBER(18,4),
    CUBICM               NUMBER(18,4),
    CAPACT               NUMBER(10),
    ZONEKY               VARCHAR2(20),
    TKZONE               VARCHAR2(20),
    AREAKY               VARCHAR2(10),
    SMANDT               VARCHAR2(10),
    SEBELN               VARCHAR2(30),
    SEBELP               VARCHAR2(10),
    SZMBLNO              VARCHAR2(30),
    SZMIPNO              VARCHAR2(10),
    STRAID               VARCHAR2(30),
    SVBELN               VARCHAR2(30),
    SPOSNR               VARCHAR2(10),
    STKNUM               VARCHAR2(20),
    STPNUM               VARCHAR2(20),
    SWERKS               VARCHAR2(10),
    SLGORT               VARCHAR2(10),
    SDATBG               VARCHAR2(20),
    STDLNR               VARCHAR2(20),
    SSORNU               VARCHAR2(30),
    SSORIT               VARCHAR2(10),
    SMBLNR               VARCHAR2(20),
    SZEILE               VARCHAR2(10),
    SMJAHR               VARCHAR2(10),
    SXBLNR               VARCHAR2(20),
    SAPSTS               VARCHAR2(10),
    SBKTXT               VARCHAR2(30),
    CREDAT               NUMBER(8),
    CRETIM               NUMBER(6),
    CREUSR               VARCHAR2(30),
    LMODAT               NUMBER(8),
    LMOTIM               NUMBER(6),
    LMOUSR               VARCHAR2(30),
    INDBZL               VARCHAR2(10),
    INDARC               VARCHAR2(10),
    UPDCHK               NUMBER(10),
    KEEPTS               VARCHAR2(10),
    CONSTRAINT PK_STKKA PRIMARY KEY (STOKKY)
);

-- ============================================================
-- Column Comments
-- ============================================================
COMMENT ON COLUMN STKKA.STOKKY IS '재고키';
COMMENT ON COLUMN STKKA.WAREKY IS '거점';
COMMENT ON COLUMN STKKA.LOTNUM IS '물류롯트넘버';
COMMENT ON COLUMN STKKA.LOCAKY IS '지번';
COMMENT ON COLUMN STKKA.TRNUID IS 'Pallet ID';
COMMENT ON COLUMN STKKA.SECTID IS 'Sect.ID';
COMMENT ON COLUMN STKKA.PACKID IS '박스ID';
COMMENT ON COLUMN STKKA.QTSIWH IS '수량';
COMMENT ON COLUMN STKKA.QTSALO IS '할당수량';
COMMENT ON COLUMN STKKA.QTSPMO IS '이동수량(OUT)';
COMMENT ON COLUMN STKKA.QTSPMI IS '이동수량(IN)';
COMMENT ON COLUMN STKKA.QTSBLK IS '보류수량';
COMMENT ON COLUMN STKKA.QTYUOM IS 'Cross수량';
COMMENT ON COLUMN STKKA.TRUNTY IS '팔렛타입';
COMMENT ON COLUMN STKKA.MEASKY IS '품목코드';
COMMENT ON COLUMN STKKA.UOMKEY IS '단위';
COMMENT ON COLUMN STKKA.QTPUOM IS '분자';
COMMENT ON COLUMN STKKA.DUOMKY IS '단위';
COMMENT ON COLUMN STKKA.QTDUOM IS '입수';
COMMENT ON COLUMN STKKA.TKFLKY IS '작업흐름키';
COMMENT ON COLUMN STKKA.STEPNO IS '단계 번호';
COMMENT ON COLUMN STKKA.LSTTFL IS '최종스텝';
COMMENT ON COLUMN STKKA.SRCSKY IS 'Src.재고';
COMMENT ON COLUMN STKKA.UOMDOC IS '참조문서 단위';
COMMENT ON COLUMN STKKA.CNTBSK IS '브런치재고수';
COMMENT ON COLUMN STKKA.NUPDPS IS 'Not update to parent stock key';
COMMENT ON COLUMN STKKA.REFDKY IS '참조문서';
COMMENT ON COLUMN STKKA.REFDIT IS '참조문서It.';
COMMENT ON COLUMN STKKA.REFCAT IS '참조문서유형';
COMMENT ON COLUMN STKKA.REFDAT IS '참조일자';
COMMENT ON COLUMN STKKA.PURCKY IS '구매오더';
COMMENT ON COLUMN STKKA.PURCIT IS '구매 It.';
COMMENT ON COLUMN STKKA.ASNDKY IS 'ASN 문서번호';
COMMENT ON COLUMN STKKA.ASNDIT IS 'ASN Item';
COMMENT ON COLUMN STKKA.RECVKY IS '입고키';
COMMENT ON COLUMN STKKA.RECVIT IS '입고순서';
COMMENT ON COLUMN STKKA.SHPOKY IS '출고문서번호';
COMMENT ON COLUMN STKKA.SHPOIT IS '출고문서아이템';
COMMENT ON COLUMN STKKA.GRPOKY IS '그룹오더';
COMMENT ON COLUMN STKKA.GRPOIT IS '그룹오더순서';
COMMENT ON COLUMN STKKA.TASKKY IS '작업지시번호';
COMMENT ON COLUMN STKKA.TASKIT IS '작업지시순서';
COMMENT ON COLUMN STKKA.SADJKY IS '조정문서번호';
COMMENT ON COLUMN STKKA.SADJIT IS '조정문서순서';
COMMENT ON COLUMN STKKA.SDIFKY IS 'Diff.No.';
COMMENT ON COLUMN STKKA.SDIFIT IS 'Diff.It.';
COMMENT ON COLUMN STKKA.PHYIKY IS '재고실사번호';
COMMENT ON COLUMN STKKA.PHYIIT IS '재고실사순번';
COMMENT ON COLUMN STKKA.OWNRKY IS '화주';
COMMENT ON COLUMN STKKA.SKUKEY IS '품목코드';
COMMENT ON COLUMN STKKA.LOTA01 IS '저장위치';
COMMENT ON COLUMN STKKA.LOTA02 IS '플랜트';
COMMENT ON COLUMN STKKA.LOTA03 IS '포장타입';
COMMENT ON COLUMN STKKA.LOTA04 IS '호기';
COMMENT ON COLUMN STKKA.LOTA05 IS 'LOTA05';
COMMENT ON COLUMN STKKA.LOTA06 IS '상태값';
COMMENT ON COLUMN STKKA.LOTA07 IS 'MTO판매번호';
COMMENT ON COLUMN STKKA.LOTA08 IS '국가코드';
COMMENT ON COLUMN STKKA.LOTA09 IS 'MTO판매처코드';
COMMENT ON COLUMN STKKA.LOTA10 IS '보류사유명';
COMMENT ON COLUMN STKKA.LOTA11 IS '제조일자';
COMMENT ON COLUMN STKKA.LOTA12 IS '입고일자';
COMMENT ON COLUMN STKKA.LOTA13 IS '유통기한';
COMMENT ON COLUMN STKKA.LOTA14 IS '개별바코드';
COMMENT ON COLUMN STKKA.LOTA15 IS '배치번호';
COMMENT ON COLUMN STKKA.LOTA16 IS '평량';
COMMENT ON COLUMN STKKA.LOTA17 IS '컨테이너유형';
COMMENT ON COLUMN STKKA.LOTA18 IS 'LOTA18';
COMMENT ON COLUMN STKKA.LOTA19 IS 'LOTA19';
COMMENT ON COLUMN STKKA.LOTA20 IS 'LOTA20';
COMMENT ON COLUMN STKKA.AWMSNO IS 'SEQ(MP)';
COMMENT ON COLUMN STKKA.DESC01 IS '품목명칭';
COMMENT ON COLUMN STKKA.DESC02 IS '규격';
COMMENT ON COLUMN STKKA.ASKU01 IS 'ERP 품번코드';
COMMENT ON COLUMN STKKA.ASKU02 IS '브랜드';
COMMENT ON COLUMN STKKA.ASKU03 IS '제조상';
COMMENT ON COLUMN STKKA.ASKU04 IS '유통기한일';
COMMENT ON COLUMN STKKA.ASKU05 IS 'Image등록유무';
COMMENT ON COLUMN STKKA.EANCOD IS '88바코드';
COMMENT ON COLUMN STKKA.GTINCD IS '바코드';
COMMENT ON COLUMN STKKA.SKUG01 IS '품목유형';
COMMENT ON COLUMN STKKA.SKUG02 IS '즉시불출여부';
COMMENT ON COLUMN STKKA.SKUG03 IS '품목유형3';
COMMENT ON COLUMN STKKA.SKUG04 IS '상품구분';
COMMENT ON COLUMN STKKA.SKUG05 IS '제품군';
COMMENT ON COLUMN STKKA.GRSWGT IS '총중량';
COMMENT ON COLUMN STKKA.NETWGT IS 'KIT순중량';
COMMENT ON COLUMN STKKA.WGTUNT IS '중량단위';
COMMENT ON COLUMN STKKA.LENGTH IS '길이';
COMMENT ON COLUMN STKKA.WIDTHW IS '가로';
COMMENT ON COLUMN STKKA.HEIGHT IS '높이';
COMMENT ON COLUMN STKKA.CUBICM IS 'CBM';
COMMENT ON COLUMN STKKA.CAPACT IS 'CAPA';
COMMENT ON COLUMN STKKA.ZONEKY IS '구역';
COMMENT ON COLUMN STKKA.TKZONE IS '작업구역';
COMMENT ON COLUMN STKKA.AREAKY IS '영역';
COMMENT ON COLUMN STKKA.SMANDT IS 'Client';
COMMENT ON COLUMN STKKA.SEBELN IS '오더번호';
COMMENT ON COLUMN STKKA.SEBELP IS '오더번호순서';
COMMENT ON COLUMN STKKA.SZMBLNO IS 'B/L NO';
COMMENT ON COLUMN STKKA.SZMIPNO IS 'B/L Item NO';
COMMENT ON COLUMN STKKA.STRAID IS 'SCM주문번호';
COMMENT ON COLUMN STKKA.SVBELN IS '출고오더번호';
COMMENT ON COLUMN STKKA.SPOSNR IS '출고오더순번';
COMMENT ON COLUMN STKKA.STKNUM IS '선적번호';
COMMENT ON COLUMN STKKA.STPNUM IS '토탈피킹선적';
COMMENT ON COLUMN STKKA.SWERKS IS '출발지';
COMMENT ON COLUMN STKKA.SLGORT IS '영업 부문';
COMMENT ON COLUMN STKKA.SDATBG IS '출하계획일시';
COMMENT ON COLUMN STKKA.STDLNR IS '작업장';
COMMENT ON COLUMN STKKA.SSORNU IS '반품출하문서번호';
COMMENT ON COLUMN STKKA.SSORIT IS '반품출하 문서아이템';
COMMENT ON COLUMN STKKA.SMBLNR IS 'Mat.Doc.';
COMMENT ON COLUMN STKKA.SZEILE IS 'Mat.Doc.';
COMMENT ON COLUMN STKKA.SMJAHR IS 'M/D 년도';
COMMENT ON COLUMN STKKA.SXBLNR IS '인터페이스번호';
COMMENT ON COLUMN STKKA.SAPSTS IS 'ERP Mvt';
COMMENT ON COLUMN STKKA.SBKTXT IS 'Text';
COMMENT ON COLUMN STKKA.CREDAT IS '생성일';
COMMENT ON COLUMN STKKA.CRETIM IS '생성시간';
COMMENT ON COLUMN STKKA.CREUSR IS '생성자';
COMMENT ON COLUMN STKKA.LMODAT IS '수정일';
COMMENT ON COLUMN STKKA.LMOTIM IS '수정시간';
COMMENT ON COLUMN STKKA.LMOUSR IS '수정자';
COMMENT ON COLUMN STKKA.INDBZL IS '비지니스로직';
COMMENT ON COLUMN STKKA.INDARC IS '아카이브 구분자';
COMMENT ON COLUMN STKKA.UPDCHK IS '수정체크';
COMMENT ON COLUMN STKKA.KEEPTS IS 'SMS';

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX IDX_STKKA_WAREKY ON STKKA (WAREKY);
CREATE INDEX IDX_STKKA_LOCAKY ON STKKA (LOCAKY);
CREATE INDEX IDX_STKKA_SKUKEY ON STKKA (SKUKEY);
CREATE INDEX IDX_STKKA_LOTNUM ON STKKA (LOTNUM);
CREATE INDEX IDX_STKKA_OWNRKY ON STKKA (OWNRKY);
CREATE INDEX IDX_STKKA_ZONEKY ON STKKA (ZONEKY);
CREATE INDEX IDX_STKKA_MEASKY ON STKKA (MEASKY);
CREATE INDEX IDX_STKKA_WAREKY_LOCAKY ON STKKA (WAREKY, LOCAKY);
CREATE INDEX IDX_STKKA_WAREKY_ZONEKY ON STKKA (WAREKY, ZONEKY);
CREATE INDEX IDX_STKKA_CREDAT ON STKKA (CREDAT);
